Repository content-services/content-sources-frontend, pull requests merged in 2022-08, with the labels that each got.

#11 Fixes 117: Container deployment files
  build_deploy.sh
  package.json
Labels: no-qe-needed

#15 Refs 146: Make build_deploy.sh executable
  build_deploy.sh
Labels: qe-testing-needed

#16 Refs 146: Fix IMAGE param
  deployments/frontend.yaml
Labels: bug

#18 Fixes 150: fixes for deployment
  deployments/frontend.yaml
  fec.config.js
  package.json
Labels: qe-testing-needed, Ready for QE

#9 Fixes 41: Add create content modal
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/AppEntry.tsx
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/components/ContentValidity.tsx
  src/components/AddContent/helpers.ts
  src/components/ContentListTable/ContentListChips.tsx
  src/components/ContentListTable/ContentListContext.tsx
  src/components/ContentListTable/ContentListFilters.tsx
  src/components/ContentListTable/ContentListTable.tsx
  src/components/ContentListTable/components/EmptyTableState.tsx
  src/components/DropdownSelect/DropdownSelect.tsx
  src/components/Error/ErrorPage.tsx
  src/pages/ContentPage/ContentPage.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
  src/services/queryHelpers.ts
Labels: qe-testing-needed

#20 Refs 150: fixes for local deployments
  deploy/frontend.yaml
  deployments
  fec.config.js
  src/pages/ContentPage/ContentPage.tsx
Labels: qe-testing-needed

#21 Refs 150: duplicate frontend.yaml
  deployments
  deployments/frontend.yaml
Labels: qe-testing-needed

#22 Refs 106: Add pr_check.sh script
  .rhcicd/build_deploy.sh
  .rhcicd/pr_check.sh
Labels: enhancement, qe-testing-needed

#17 Fixes 102: Add front-end tests
  .vscode/settings.json
  .watchmanconfig
  deployments/frontend.yaml
  package.json
  src/AppEntry.tsx
  src/Routes.tsx
  src/components/AddContent/AddContent.test.tsx
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/components/ContentValidity.tsx
  src/components/AddContent/helpers.test.ts
  src/components/AddContent/helpers.ts
  src/components/AddContent/httpErrorCodes.json
  src/components/ContentListTable/ContentListFilters.tsx
  src/components/ContentListTable/ContentListTable.test.tsx
  src/components/ContentListTable/components/EmptyTableState.test.tsx
  src/components/ContentListTable/components/EmptyTableState.tsx
  src/components/DropdownSelect/DropDownSelect.test.tsx
  src/components/Error/ErrorPage.test.tsx
  src/components/Error/ErrorPage.tsx
  src/components/Hide/Hide.test.tsx
  src/components/SampleComponent/sample-component.scss
  src/components/SampleComponent/sample-component.test.tsx
  src/components/SampleComponent/sample-component.tsx
  src/services/Content/ContentApi.ts
  src/testingHelpers.tsx
Labels: no-qe-needed

#23 Refs 106: Set NODE_BUILD_VERSION from .nvmrc in pr_check
  .rhcicd/pr_check.sh
Labels: enhancement, no-qe-needed

#25 Refs 118: Add ouiaID to AddContent button
  src/components/AddContent/AddContent.tsx
  src/components/ContentListTable/components/EmptyTableState.tsx
Labels: enhancement, qe-testing-needed
