Repository content-services/content-sources-frontend, pull requests merged in 2022-09, with the labels that each got.

#28 Refs 118: ouia ID for add modal
  src/components/AddContent/AddContent.tsx
Labels: enhancement, qe-testing-needed

#27 Fixes 112: Add #pkgs to the repository table
  src/components/ContentListTable/ContentListTable.test.tsx
  src/components/ContentListTable/ContentListTable.tsx
  src/services/Content/ContentApi.ts
Labels: qe-testing-needed, Ready for QE

#24 Fixes 52: Add EditContent Modal
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/helpers.ts
  src/components/ContentListTable/ContentListFilters.tsx
  src/components/ContentListTable/ContentListTable.tsx
  src/components/EditContentModal/EditContentModal.test.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/components/EditContentModal/helpers.test.ts
  src/components/EditContentModal/helpers.ts
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
Labels: qe-testing-needed, Ready for QE

#32 Refs 166: Load 20 real urls
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/helpers.ts
Labels: qe-testing-needed

#31 Fixes 163: Add Any version/Any architecture options
  src/components/AddContent/AddContent.tsx
  src/components/ContentListTable/ContentListTable.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/testingHelpers.tsx
Labels: qe-testing-needed, Ready for QE

#29 Fixes 161: Add introspection status column to list table
  src/components/ContentListTable/ContentListTable.tsx
  src/components/ContentListTable/components/StatusIcon.test.tsx
  src/components/ContentListTable/components/StatusIcon.tsx
  src/components/ContentListTable/components/StatusText.tsx
  src/components/EditContentModal/EditContentModal.test.tsx
  src/components/EditContentModal/helpers.test.ts
  src/services/Content/ContentApi.ts
Labels: qe-testing-needed, Ready for QE

#33 Fixes 176: add list sorting
  src/components/ContentListTable/ContentListTable.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
Labels: qe-testing-needed, Ready for QE

#36 Fixes 77: add gpg key and verification option
  src/components/AddContent/AddContent.test.tsx
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/helpers.test.ts
  src/components/AddContent/helpers.ts
  src/components/ContentListTable/ContentListTable.tsx
  src/components/ContentListTable/components/StatusIcon.test.tsx
  src/components/ContentListTable/components/StatusIcon.tsx
  src/components/ContentListTable/components/StatusText.tsx
  src/components/EditContentModal/EditContentModal.test.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/components/EditContentModal/helpers.test.ts
  src/components/EditContentModal/helpers.ts
  src/services/Content/ContentApi.ts
Labels: qe-testing-needed

#34 Fixes 158: Update UI to match demo Mocks
  src/components/AddContent/AddContent.test.tsx
  src/components/AddContent/AddContent.tsx
  src/components/ContentListTable/ContentListFilters.tsx
  src/components/ContentListTable/ContentListTable.test.tsx
  src/components/ContentListTable/ContentListTable.tsx
  src/components/ContentListTable/components/EmptyTableState.test.tsx
  src/components/ContentListTable/components/EmptyTableState.tsx
  src/components/ContentListTable/components/PackageCount.tsx
  src/components/ContentListTable/components/StatusIcon.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/components/Error/ErrorPage.test.tsx
  src/components/Error/ErrorPage.tsx
  src/components/UrlWithLinkIcon/UrlWithLinkIcon.tsx
  src/pages/ContentPage/ContentPage.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
Labels: qe-testing-needed
