Repository content-services/content-sources-frontend, pull requests merged in 2022-10, with the labels that each got.

#44 Refs 214: cache build for later deploy
  .github/workflows/content-sources-actions.yml
Labels: qe-testing-needed

#38 Fixes 208: Add api validation for gpg-keys
  src/components/AddContent/AddContent.test.tsx
  src/components/AddContent/AddContent.tsx
  src/components/AddContent/helpers.test.ts
  src/components/AddContent/helpers.ts
  src/components/EditContentModal/EditContentModal.test.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/components/Error/ErrorPage.test.tsx
  src/components/OptionalTooltip/OptionalTooltip.test.tsx
  src/components/OptionalTooltip/OptionalTooltip.tsx
  src/services/Content/ContentApi.ts
  src/testingHelpers.tsx
Labels: no-qe-needed

#35 Fixes 76: Allow Pasting of URL for GPGKey using API
  src/components/AddContent/AddContent.test.tsx
  src/components/AddContent/AddContent.tsx
  src/components/ContentListTable/ContentListTable.test.tsx
  src/components/EditContentModal/EditContentModal.test.tsx
  src/components/EditContentModal/EditContentModal.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
Labels: qe-testing-needed, Ready for QE

#48 Refs 184: add ouia and tooltips
  src/components/AddContent/AddContent.tsx
  src/components/EditContentModal/EditContentModal.tsx
Labels: qe-testing-needed

#45 Fixes 216: Restructure frontend components
  src/components/ContentListTable/ContentListTable.tsx
  src/components/ContentListTable/components/AddContent/AddContent.test.tsx
  src/components/ContentListTable/components/AddContent/AddContent.tsx
  src/components/ContentListTable/components/AddContent/components/ContentValidity.tsx
  src/components/ContentListTable/components/AddContent/helpers.test.ts
  src/components/ContentListTable/components/AddContent/helpers.ts
  src/components/ContentListTable/components/AddContent/httpErrorCodes.json
  src/components/ContentListTable/components/ContentListFilters.tsx
  src/components/ContentListTable/components/EditContentModal/EditContentModal.test.tsx
  src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx
  src/components/ContentListTable/components/EditContentModal/helpers.test.ts
  src/components/ContentListTable/components/EditContentModal/helpers.ts
  src/components/ContentListTable/components/EmptyTableState.tsx
  src/components/ContentListTable/components/UrlWithLinkIcon/UrlWithLinkIcon.tsx
Labels: no-qe-needed

#50 Refs 184: add ouia ID for name and url
  src/components/ContentListTable/components/AddContent/AddContent.tsx
  src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx
Labels: qe-testing-needed

#51 Refs 184: Add ouiaIds to DropdownSelect
  src/components/ContentListTable/components/AddContent/AddContent.tsx
  src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx
Labels: qe-testing-needed

#52 Fixes 230: Fix UI redirect to /content
  fec.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/Routes.tsx
  src/pages/NoPermissionsPage/NoPermissionsPage.tsx
  src/pages/OopsPage/OopsPage.tsx
Labels: qe-testing-needed, Ready for QE

#56 Refs 184: Add ouiaid for edit modal buttons
  src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx
Labels: qe-testing-needed
