Repository content-services/content-sources-frontend, pull requests merged in 2024-08, with the labels that each got.

#313 Fixes 4372: Update Axios, replace old RBAC client
  package-lock.json
  package.json
  src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx
  src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx
  src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx
  src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.tsx
  src/Routes/Repositories/useRepositoryRoutes.tsx
  src/middleware/AppContext.tsx
  src/middleware/RbacUtils.ts
Labels: no-qe-needed

#318 Fixes 3938: Fix admin task polling
  src/Pages/Repositories/AdminTaskTable/AdminTaskTable.tsx
  src/services/AdminTasks/AdminTaskQueries.ts
Labels: qe-testing-needed, Ready for QE

#314 Fixes 4524: Fix menu routing for popular repos
  src/Pages/Repositories/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.tsx
  src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx
  src/Pages/Repositories/RepositoryLayout.tsx
  src/Routes/constants.ts
  src/Routes/index.tsx
Labels: qe-testing-needed, Ready for QE

#321 Fixes 4587: ZeroState, Node modules, eslint, fec-config
  .eslintignore
  .eslintrc.json
  eslint.config.mjs
  fec.config.js
  package-lock.json
  package.json
  src/Pages/Templates/TemplatesTable/components/AddTemplate/AddNavigateButton.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplateContext.tsx
  src/Routes/index.tsx
  src/components/DropdownMenu/DropdownMenu.tsx
  src/components/DropdownSelect/DropdownSelect.tsx
  src/components/ZeroState/ZeroState.tsx
Labels: qe-testing-needed, Ready for QE

#319 Refs 4426: Enforce external,upload for custom repositories
  src/App.tsx
  src/Pages/Repositories/ContentListTable/ContentListTable.test.tsx
  src/Pages/Repositories/ContentListTable/ContentListTable.tsx
  src/Pages/Repositories/ContentListTable/components/ContentListFilters.test.tsx
  src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx
  src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.test.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataTab.test.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotPackagesTab.test.tsx
  src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/CustomRepositoriesStep.tsx
  src/middleware/AppContext.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
Labels: no-qe-needed

#325 Refs 4297: fix zero date format, add UTC tooltip
  src/Pages/Templates/TemplateDetails/components/Tabs/TemplateErrataTab.test.tsx
  src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplateContext.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.test.tsx
  src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx
  src/Pages/Templates/TemplatesTable/components/templateHelpers.test.ts
  src/Pages/Templates/TemplatesTable/components/templateHelpers.ts
  src/helpers.ts
Labels: qe-testing-needed
