Repository content-services/content-sources-frontend, pull requests merged in 2024-11, with the labels that each got.

#370 Fixes 4918: missing invalidation on introspection
  src/services/Content/ContentQueries.ts
Labels: qe-testing-needed, Ready for QE

#371 Fixes 4913: Update zero-state button to PF5
  src/components/ZeroState/ZeroState.tsx
Labels: qe-testing-needed

#368 Fixes 4763: Add hover text pop up in Edit rpm upload modal
  src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
Labels: qe-testing-needed, Ready for QE

#386 Fixes 5035: enable uploads in prod preview
  src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.test.tsx
  src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
Labels: no-qe-needed

#373 Fixes 4743: add delete and bulk delete of snapshots
  src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.test.tsx
  src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
  src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/DeleteSnapshotsModal/DeleteSnapshotsModal.test.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/DeleteSnapshotsModal/DeleteSnapshotsModal.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.test.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/components/LatestRepoConfig.tsx
  src/Pages/Repositories/ContentListTable/components/SnapshotListModal/components/RepoConfig.tsx
  src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
  src/Pages/Templates/TemplatesTable/components/TemplateFilters.test.tsx
  src/Pages/Templates/TemplatesTable/components/TemplateFilters.tsx
  src/Routes/index.tsx
  src/services/Content/ContentApi.ts
  src/services/Content/ContentQueries.ts
  src/services/Templates/TemplateApi.ts
  src/services/Templates/TemplateQueries.ts
  src/testingHelpers.tsx
Labels: qe-testing-needed, Ready for QE
